SUCCESS=0
ERROR_UNKNOWN=-1
ERROR_EMPTY_EMAIL_PASS=1
ERROR_WRONG_EMAIL_PASS=2
ERROR_USED_EMAIL=3
ERROR_USED_SERIAL=4
ERROR_UNK_SERIAL=5
ERROR_CONNECTION = 6



REQ_OPEN_DOOR = 7
REQ_CLOSE_DOOR = 8
REQ_PULL_BAIT = 9
REQ_PUSH_BAIT = 10
REQ_TAKE_PHOTO = 11



GPIO_PIN_MOTION_SENSOR = 5
GPIO_PIN_DIST_SENSOR_TRIG = 17
GPIO_PIN_DIST_SENSOR_ECHO = 27

GPIO_PIN_STEP_1 = 6
GPIO_PIN_STEP_2 = 16
GPIO_PIN_STEP_3 = 19
GPIO_PIN_STEP_4 = 26

GPIO_PIN_DC_1 = 20
GPIO_PIN_DC_2 = 21
GPIO_PIN_DC_PWM = 18



